### ISSUE TITLE
Video tutorial (FPGA programming)

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#10]
Pogledati video na sljedećem linku:

https://youtu.be/D-kIoQWeO_E

**Kriterijumi prihvatanja:**

- Prezentovani koncepti su potpuno razumljivi
- Dati primjeri su reprodukovani u lokalnom okruženju

**Comment by lukavidic** [comment]
Completed

**Comment by nemanjatr** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by dleg98** [comment]
Completed

**Comment by bsav98** [comment]
Completed

**Comment by Neira7** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed
