### ISSUE TITLE
Video tutorial (FPGA basics)

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#3]
Pogledati video na sljedećem linku:

https://youtu.be/oJSAv1hhdgk

**Kriterijumi prihvatanja:**

- Prezentovani koncepti su potpuno razumljivi

**Comment by lukavidic** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by dleg98** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed

**Comment by bsav98** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed

**Comment by Neira7** [comment]
Completed
