### ISSUE TITLE
Get familiar with project workflow in GitHub

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#4]
Upoznati se sa [procesom rada u GitHub okruženju](https://github.com/etf-unibl/pds-2023/blob/main/docs/github-workflow.md), kao i sa [pravilima prilikom predavanja rješenja zadataka](https://github.com/etf-unibl/pds-2023/blob/main/docs/git-commit.md). Datim linkovima se može pristupiti i iz glavne stranice u repozitorijumu.

**Comment by lukavidic** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by bsav98** [comment]
Completed

**Comment by dleg98** [comment]
Completed

**Comment by bsav98** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed

**Comment by Neira7** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed
