### ISSUE TITLE
Install and configure Git environment

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#5]
Potrebno je instalirati i konfigurisati Git okruženje u skladu sa instrukcijama koje su date na glavnoj stranici repozitorijuma (sekcija [Podešavanje Git okruženja za omogućenje pristupa repozitorijumu](https://github.com/etf-unibl/pds-2023/blob/main/docs/git-setup.md)).

**Kriterijumi prihvatanja:**

- Git alat je instaliran što se potvrđuje uspješnim kloniranjem repozitorijuma kursa

**Comment by nemanjatr** [comment]
Completed

**Comment by lukavidic** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by dleg98** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed

**Comment by Neira7** [comment]
Completed
