### ISSUE TITLE
Install and configure Clockify

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#6]
Potrebno je napraviti [Clockify](https://clockify.me/) nalog, a zatim instalirati Chrome dodatak za evidenciju vremena unutar GitHub okruženja. Instrukcije se mogu pronaći na sljedećem linku:

https://clockify.me/github-time-tracking

**Kriterijumi prihvatanja:**

- Kreiran nalog i podešeno Clockify okruženje tako da je student registrovan u okviru workspace-a kursa PDS-2023
- Vrijeme se može logovati u GitHub okruženju korišćenjem odgovarajućeg dodatka

**Comment by nemanjatr** [comment]
Completed

**Comment by lukavidic** [comment]
Completed

**Comment by RadonicA** [comment]
Completed

**Comment by dleg98** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed

**Comment by Neira7** [comment]
Completed
