### ISSUE TITLE
Install and configure Quartus software tools

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2023#8]
Instalirati i konfigurisati **Intel Quartus Prime 20.1 Lite Edition** skup softverskih alata. Preporučena uputstva za instalaciju:

1. Postupak instalacije za različite platforme (link: https://github.com/Jefferson-Lopes/quartus-installation)
2. Video uputstvo za Windows platformu (link: https://www.youtube.com/watch?v=u84s8JY69Nw)

**Kriterijumi prihvatanja:**

- Instaliran kompletan skup alata uključujući i **ModelSim**
- Instalirana je verzija **Intel Quartus Prime 20.1 Lite Edition**
- Instalirani softver je operativan i spreman za korišćenje u lokalnom okruženju

**Comment by lukavidic** [comment]
Completed

**Comment by nemanjatr** [comment]
Completed

**Comment by bsav98** [comment]
Complited

**Comment by dleg98** [comment]
Complited

**Comment by dleg98** [comment]
Completed

**Comment by AnjaDj** [comment]
Completed

**Comment by Neira7** [comment]
Completed

**Comment by NikolaBabic1213** [comment]
Completed
